<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite thread-count="2" parallel="tests" name="Failed suite [Suite]" guice-stage="DEVELOPMENT" verbose="0">
  <test thread-count="2" parallel="tests" name="error validation(failed)" verbose="0">
    <classes>
      <class name="com.TestingFolder.ErrorValidation">
        <methods>
          <include name="launchApplication"/>
          <include name="close"/>
          <include name="loginErrorValidation"/>
        </methods>
      </class> <!-- com.TestingFolder.ErrorValidation -->
    </classes>
  </test> <!-- error validation(failed) -->
  <test thread-count="2" parallel="tests" name="SubmitOrder(failed)" verbose="0">
    <classes>
      <class name="com.TestingFolder.SubmitOrderTest">
        <methods>
          <include name="launchApplication"/>
          <include name="close"/>
          <include name="orderHistory"/>
          <include name="submitOrder" invocation-numbers="1"/>
        </methods>
      </class> <!-- com.TestingFolder.SubmitOrderTest -->
    </classes>
  </test> <!-- SubmitOrder(failed) -->
</suite> <!-- Failed suite [Suite] -->
